addresses:
  - tcp://127.0.0.1:1883
  - ssl://127.0.0.1:1884
  - ws://127.0.0.1:8883/mqtt
  - wss://127.0.0.1:8884/mqtt
certificate:
  ca: example/testcert/ca.pem
  cert: example/testcert/server.pem
  key: example/testcert/server.key
principals:
  - username: test
    password: hahaha
    permissions:
      - action: pub
        permit: ["test", "#"]
      - action: sub
        permit: ["test", "#"]
  - username: client.example.org
    permissions:
      - action: pub
        permit: ["test", "#"]
      - action: sub
        permit: ["test", "#"]
session:
  sysTopics: ["$link", "$baidu"]
