// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Context              *Context `protobuf:"bytes,1,opt,name=Context,proto3" json:"Context,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Context struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TS                   uint64   `protobuf:"varint,2,opt,name=TS,proto3" json:"TS,omitempty"`
	QOS                  uint32   `protobuf:"varint,3,opt,name=QOS,proto3" json:"QOS,omitempty"`
	Retain               uint32   `protobuf:"varint,4,opt,name=Retain,proto3" json:"Retain,omitempty"`
	Topic                string   `protobuf:"bytes,5,opt,name=Topic,proto3" json:"Topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Context) GetTS() uint64 {
	if m != nil {
		return m.TS
	}
	return 0
}

func (m *Context) GetQOS() uint32 {
	if m != nil {
		return m.QOS
	}
	return 0
}

func (m *Context) GetRetain() uint32 {
	if m != nil {
		return m.Retain
	}
	return 0
}

func (m *Context) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "common.Message")
	proto.RegisterType((*Context)(nil), "common.Context")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xce, 0xcf, 0xcd, 0xcd,
	0xcf, 0x53, 0xf2, 0xe3, 0x62, 0xf7, 0x85, 0x48, 0x08, 0x69, 0x72, 0xb1, 0x3b, 0xe7, 0xe7, 0x95,
	0xa4, 0x56, 0x94, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xeb, 0x41, 0x14, 0xe9, 0x41,
	0x85, 0x83, 0x60, 0xf2, 0x42, 0x12, 0x50, 0xa5, 0x79, 0x25, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c,
	0x41, 0x30, 0xae, 0x52, 0x26, 0xdc, 0x10, 0x21, 0x3e, 0x2e, 0x26, 0x4f, 0x17, 0xb0, 0x51, 0x2c,
	0x41, 0x4c, 0x9e, 0x2e, 0x20, 0x7e, 0x48, 0x30, 0x58, 0x3d, 0x4b, 0x10, 0x53, 0x48, 0xb0, 0x90,
	0x00, 0x17, 0x73, 0xa0, 0x7f, 0xb0, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x88, 0x29, 0x24,
	0xc6, 0xc5, 0x16, 0x94, 0x5a, 0x92, 0x98, 0x99, 0x27, 0xc1, 0x02, 0x16, 0x84, 0xf2, 0x84, 0x44,
	0xb8, 0x58, 0x43, 0xf2, 0x0b, 0x32, 0x93, 0x25, 0x58, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x9c,
	0x24, 0x36, 0xb0, 0x4f, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x38, 0x3d, 0x32, 0x87, 0xda,
	0x00, 0x00, 0x00,
}
