name: unittest
on: pull_request

jobs:
  test:
    name: unittest
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Dependency
        run: |
          sudo apt-get install -y libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
          git clone https://github.com/facebook/rocksdb.git
          cd rocksdb
          make shared_lib
          sudo cp librocksdb.so /usr/local/lib
          sudo mkdir -p /usr/local/include/rocksdb/
          sudo cp -r ./include/* /usr/local/include/
          cd ..
      - name: Build
        run: make all
      - name: Run unittest
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
